version: '3'

services:
  app:
    container_name: tocomplete-alphablog
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/alphablog'
    ports:
      - '8080:3000'
    tty: true
    stdin_open: true

  

